### PR TITLE
Activate TypeScript type definitions

### PR DESCRIPTION
**Pull request by akoenig**
This PR activates the creation of TypeScript type definition files which is especially useful if you want to use the library in a TS project.

Edit: The changeset is quite big, because I had to apply the ESLint formatting before committing.

### CODE REVIEW

**Comment by paambaati** [comment]
@akoenig Thanks for this PR!

The project already has ESLint rules set up and enforced, so I'm not sure how there's such a huge changeset. Simply running `yarn lint` and `yarn lint:fix` will inform you of lint errors and also try to auto-fix them.

Would you mind sending only the single change in `tsconfig.json`?

**Comment by akoenig** [comment]
@paambaati You’re welcome. So the pre-commit hook in the repository informed me about linting problems. That is why I executed a `npm run format` which then formatted untouched files. This can be reproduced when checking out the `master` branch.

**Comment by paambaati** [comment]
@akoenig Strange, because right now on `master`, there's only 1 lint error (I decided to not fix it for now because work's anyways stalled on the gRPC front).

```
$ yarn format
yarn run v1.19.1
$ eslint --fix --ext .ts src/ && eslint --fix --config .eslintrc.test.json --ext .ts test/

/Users/apple/Projects/node-liftbridge/src/index.ts
  207:1  error  This line has a length of 220. Maximum allowed is 180  max-len

✖ 1 problem (1 error, 0 warnings)
```

**Comment by akoenig** [comment]
@paambaati Ya, the pre-commit hook forces you to fix this linting problem. After fixing it and trying to commit again, the next linting error occurs:

```sh
husky > pre-commit (node v10.17.0)
yarn run v1.19.1
$ eslint --ext .ts src/
✨  Done in 3.77s.
yarn run v1.19.1
$ eslint --config .eslintrc.test.json --ext .ts test/

...metadata.test.ts
  140:15  error  'metadata' is already declared in the upper scope  no-shadow

✖ 1 problem (1 error, 0 warnings)
```

So I ended up fixing all following linting errors 🙂

**Comment by paambaati** [comment]
@akoenig I've fixed the 2 lint errors I got. Can you rebase against `master`? The PR diff should then be only a single line.

**Comment by akoenig** [comment]
Done. Thanks @paambaati

**Pull request merged**
